### ISSUE TITLE
Reply with Group Number and Class Section

### ISSUE THREAD

**Issue by ProfRojas** [danieltran67/All-In-One-Agenda#1]

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by danieltran67** [comment]
Hello World!

**Comment by saeed-97** [comment]
Hi

**Comment by anthonynguyent** [comment]
hello

**Comment by AntonioMagana** [comment]
Hello

**Comment by ProfRojas** [comment]
I also need to know your group number and class section.

**Comment by danieltran67** [comment]
Team 11;Cmpe131 section 5

**Comment by ProfRojas** [comment]
Thanks!
