### ISSUE TITLE
[HELP]Every user sees my Google Calendar!

### ISSUE THREAD

**Issue by danieltran67** [danieltran67/All-In-One-Agenda#10]
i got the googleapi to work. but maybe it was too well...
no matter what account I used to log in, it looks at danieltran150@gmail.com's Google Calendar.
how do I get it to log in to their own account?

**Comment by ProfRojas** [comment]
I couldn't run your app. Is keyring a library or a file you defined?

**Comment by danieltran67** [comment]
it is part of yagmail and is needed to make yagmail work
