### ISSUE TITLE
Flask Testing

### ISSUE THREAD

**Issue by danieltran67** [danieltran67/All-In-One-Agenda#12]
Get a working TravisCI. Then write 8-unit test for the some of the functionality of your application

**Comment by danieltran67** [comment]
I am trying to run TravisCI and the build keeps failing because of this error:

**RuntimeError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.**

I tried googling it and I cant the solution for it.

**Comment by carlosrojas** [comment]
you need Requirements.txt file

**Comment by danieltran67** [comment]
i already have requirements.txt in the new repository and even updated it via pip freeze

**Comment by carlosrojas** [comment]
The file should be in the base directory. I don't think travis-ci will find it within the folder it's currently in.

**Comment by danieltran67** [comment]
i believe requirements.txt is in the base directory in Daniel-UnitTest branch. this is quite strange

**Comment by danieltran67** [comment]
WOW i thought this issue was going to only to be for TravisCI but when I tried deploying Heroku it gave me an error and when i checked heroku log, 

2**019-12-03T07:45:49.576255+00:00 app[web.1]: RuntimeError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.**

this is going to be a fun night 👍

**Comment by danieltran67** [comment]
Nvm i figured it out. I had to type this command to fix the error
**pip install keyrings.alt**
